- branches:
    only:
    - develop
  version: 0.1.{build}
  skip_tags: true
  image: Visual Studio 2015
  install:
  - cmd: nuget restore
  init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  before_build:
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\Inno Setup 5\;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\
  build_script:
  - cmd: msbuild /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release
  after_build:
  - cmd: >- 
	xcopy "%APPVEYOR_BUILD_FOLDER%\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDna.xll" "%APPVEYOR_BUILD_FOLDER%\Requests\bin\Release\Requests64.xll*" /C /Y

    "%APPVEYOR_BUILD_FOLDER%\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDnaPack.exe" "%APPVEYOR_BUILD_FOLDER%\Requests\bin\Release\Requests.dna" /Y

    "%APPVEYOR_BUILD_FOLDER%\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDnaPack.exe" "%APPVEYOR_BUILD_FOLDER%\Requests\bin\Release\Requests64.dna" /Y


  test_script:
  - cmd: nunit3-console %APPVEYOR_BUILD_FOLDER%\Requests\bin\Release\RequestsTest.dll --result=myresults.xml;format=AppVeyor



  xcopy "$(SolutionDir)\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDna64.xll" "$(TargetDir)Requests-AddIn64.xll*" /C /Y
"$(SolutionDir)\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDnaPack.exe" "$(TargetDir)Requests-AddIn.dna" /Y
"$(SolutionDir)\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDnaPack.exe" "$(TargetDir)Requests-AddIn64.dna" /Y