- branches:
    only:
    - develop
  version: 0.1.{build}
  skip_tags: true
  image: Visual Studio 2015
  install:
  - cmd: nuget restore
  init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  before_build:
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\Inno Setup 5\;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\
  build_script:
  - cmd: msbuild /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release
  after_build:
  - cmd: xcopy "%APPVEYOR_BUILD_FOLDER%\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDna.xll" "%APPVEYOR_BUILD_FOLDER%\Requests\bin\Release\Requests.xll*" /C /Y
  - cmd: xcopy "%APPVEYOR_BUILD_FOLDER%\Requests\bin\Release\Requests.dna" "%APPVEYOR_BUILD_FOLDER%\Requests\bin\Release\Requests64.dna*" /C /Y
  - cmd: xcopy "%APPVEYOR_BUILD_FOLDER%\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDna64.xll" "%APPVEYOR_BUILD_FOLDER%\Requests\bin\Release\Requests64.xll*" /C /Y
  - cmd: xcopy "%APPVEYOR_BUILD_FOLDER%\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDnaPack.exe" "%APPVEYOR_BUILD_FOLDER%\Requests\bin\Release\Requests.dna" /Y
  - cmd: xcopy "%APPVEYOR_BUILD_FOLDER%\packages\ExcelDna.AddIn.0.33.9\tools\ExcelDnaPack.exe" "%APPVEYOR_BUILD_FOLDER%\Requests\bin\Release\Requests64.dna" /Y
  - ps: Get-ChildItem .\*.xll | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - appveyor PushArtifact Requests\bin\Release\Requests-packed.xll -FileName Requests.xll -DeploymentName Requests.xll
  - appveyor PushArtifact Requests\bin\Release\Requests64-packed.xll -FileName Requests64.xll -DeploymentName Requests64.xll
  test_script:
  - cmd: nunit3-console %APPVEYOR_BUILD_FOLDER%\RequestsTest\bin\Release\RequestsTest.dll --result=myresults.xml;format=AppVeyor

  deploy:
    release: excel-requests-v$(appveyor_build_version)
    description: 'Excel Requests'
    provider: GitHub
    auth_token:
      secure: 6ekcaIHA+U5OoEkJ/NqFxDPTz41QEtLgLXZEG0WS9MMUDADoNjEKJ5XVtnZ+Agleq/dE5traDq8DwMQVS/pcMoRUf3N1PPsFFvFqGvO/15w=
    artifact: /.*\.xll/
    draft: false
    prerelease: false
